version: '3'
services:
  nakamoto-miner-1:
    image: nakamoto-miner:latest
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
    # Don't mount the app folder. This will be explicitly copied by the dockerfile so that
    # the container files live independent of the host.
      - /root/.commune:/root/.commune
      - ./logs:/logs
    env_file:
    - ./anthropic_key.env
    environment:
      - ANTHROPIC_MODEL=claude-3-opus-20240229
      - ANTHROPIC_MAX_TOKENS=1000
      - ANTHROPIC_TEMPERATURE=0.7168854
      - PORT=8080
    ports:
      - 8080:8080
    working_dir: /app
    command: ["/bin/bash", "-c", "/app/startup_script.sh"]